package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdmAdjuntoTipoMime generated by hbm2java
 */
public class AdmAdjuntoTipoMime  implements java.io.Serializable {


     private byte idAdjuntoTipoMime;
     private String tipoMime;
     private String descripcion;
     private String extension;
     private Set congrAdjuntos = new HashSet(0);

    public AdmAdjuntoTipoMime() {
    }

	
    public AdmAdjuntoTipoMime(byte idAdjuntoTipoMime, String tipoMime, String descripcion, String extension) {
        this.idAdjuntoTipoMime = idAdjuntoTipoMime;
        this.tipoMime = tipoMime;
        this.descripcion = descripcion;
        this.extension = extension;
    }
    public AdmAdjuntoTipoMime(byte idAdjuntoTipoMime, String tipoMime, String descripcion, String extension, Set congrAdjuntos) {
       this.idAdjuntoTipoMime = idAdjuntoTipoMime;
       this.tipoMime = tipoMime;
       this.descripcion = descripcion;
       this.extension = extension;
       this.congrAdjuntos = congrAdjuntos;
    }
   
    public byte getIdAdjuntoTipoMime() {
        return this.idAdjuntoTipoMime;
    }
    
    public void setIdAdjuntoTipoMime(byte idAdjuntoTipoMime) {
        this.idAdjuntoTipoMime = idAdjuntoTipoMime;
    }
    public String getTipoMime() {
        return this.tipoMime;
    }
    
    public void setTipoMime(String tipoMime) {
        this.tipoMime = tipoMime;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public Set getCongrAdjuntos() {
        return this.congrAdjuntos;
    }
    
    public void setCongrAdjuntos(Set congrAdjuntos) {
        this.congrAdjuntos = congrAdjuntos;
    }




}


