package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AdmModuloSistema generated by hbm2java
 */
public class AdmModuloSistema  implements java.io.Serializable {


     private BigDecimal idModuloSistema;
     private String nombreModulo;
     private Set segRols = new HashSet(0);

    public AdmModuloSistema() {
    }

	
    public AdmModuloSistema(BigDecimal idModuloSistema, String nombreModulo) {
        this.idModuloSistema = idModuloSistema;
        this.nombreModulo = nombreModulo;
    }
    public AdmModuloSistema(BigDecimal idModuloSistema, String nombreModulo, Set segRols) {
       this.idModuloSistema = idModuloSistema;
       this.nombreModulo = nombreModulo;
       this.segRols = segRols;
    }
   
    public BigDecimal getIdModuloSistema() {
        return this.idModuloSistema;
    }
    
    public void setIdModuloSistema(BigDecimal idModuloSistema) {
        this.idModuloSistema = idModuloSistema;
    }
    public String getNombreModulo() {
        return this.nombreModulo;
    }
    
    public void setNombreModulo(String nombreModulo) {
        this.nombreModulo = nombreModulo;
    }
    public Set getSegRols() {
        return this.segRols;
    }
    
    public void setSegRols(Set segRols) {
        this.segRols = segRols;
    }




}


