package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdmTipoIdentificacion generated by hbm2java
 */
public class AdmTipoIdentificacion  implements java.io.Serializable {


     private byte idTipoIdentificacion;
     private String nombreTipoIdentificacion;
     private Set expPersonas = new HashSet(0);

    public AdmTipoIdentificacion() {
    }

	
    public AdmTipoIdentificacion(byte idTipoIdentificacion, String nombreTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
        this.nombreTipoIdentificacion = nombreTipoIdentificacion;
    }
    public AdmTipoIdentificacion(byte idTipoIdentificacion, String nombreTipoIdentificacion, Set expPersonas) {
       this.idTipoIdentificacion = idTipoIdentificacion;
       this.nombreTipoIdentificacion = nombreTipoIdentificacion;
       this.expPersonas = expPersonas;
    }
   
    public byte getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(byte idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public String getNombreTipoIdentificacion() {
        return this.nombreTipoIdentificacion;
    }
    
    public void setNombreTipoIdentificacion(String nombreTipoIdentificacion) {
        this.nombreTipoIdentificacion = nombreTipoIdentificacion;
    }
    public Set getExpPersonas() {
        return this.expPersonas;
    }
    
    public void setExpPersonas(Set expPersonas) {
        this.expPersonas = expPersonas;
    }




}


