package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CongrSala generated by hbm2java
 */
public class CongrSala  implements java.io.Serializable {


     private BigDecimal idSala;
     private CongrCongreso congrCongreso;
     private String nombre;
     private String descripcion;
     private Set congrSesions = new HashSet(0);

    public CongrSala() {
    }

	
    public CongrSala(BigDecimal idSala, CongrCongreso congrCongreso, String nombre, String descripcion) {
        this.idSala = idSala;
        this.congrCongreso = congrCongreso;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public CongrSala(BigDecimal idSala, CongrCongreso congrCongreso, String nombre, String descripcion, Set congrSesions) {
       this.idSala = idSala;
       this.congrCongreso = congrCongreso;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.congrSesions = congrSesions;
    }
   
    public BigDecimal getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(BigDecimal idSala) {
        this.idSala = idSala;
    }
    public CongrCongreso getCongrCongreso() {
        return this.congrCongreso;
    }
    
    public void setCongrCongreso(CongrCongreso congrCongreso) {
        this.congrCongreso = congrCongreso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCongrSesions() {
        return this.congrSesions;
    }
    
    public void setCongrSesions(Set congrSesions) {
        this.congrSesions = congrSesions;
    }




}


