package entidades;
// Generated 27/06/2016 06:34:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;

/**
 * CongrAdjunto generated by hbm2java
 */
public class CongrAdjunto  implements java.io.Serializable {


     private BigDecimal idAdjunto;
     private AdmAdjuntoTipoMime admAdjuntoTipoMime;
     private CongrCongreso congrCongreso;
     private CongrTrabajoAcademico congrTrabajoAcademico;
     private String nombre;
     private String descripcion;
     private Blob archivo;

    public CongrAdjunto() {
    }

    public CongrAdjunto(BigDecimal idAdjunto, AdmAdjuntoTipoMime admAdjuntoTipoMime, CongrCongreso congrCongreso, CongrTrabajoAcademico congrTrabajoAcademico, String nombre, String descripcion, Blob archivo) {
       this.idAdjunto = idAdjunto;
       this.admAdjuntoTipoMime = admAdjuntoTipoMime;
       this.congrCongreso = congrCongreso;
       this.congrTrabajoAcademico = congrTrabajoAcademico;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.archivo = archivo;
    }
   
    public BigDecimal getIdAdjunto() {
        return this.idAdjunto;
    }
    
    public void setIdAdjunto(BigDecimal idAdjunto) {
        this.idAdjunto = idAdjunto;
    }
    public AdmAdjuntoTipoMime getAdmAdjuntoTipoMime() {
        return this.admAdjuntoTipoMime;
    }
    
    public void setAdmAdjuntoTipoMime(AdmAdjuntoTipoMime admAdjuntoTipoMime) {
        this.admAdjuntoTipoMime = admAdjuntoTipoMime;
    }
    public CongrCongreso getCongrCongreso() {
        return this.congrCongreso;
    }
    
    public void setCongrCongreso(CongrCongreso congrCongreso) {
        this.congrCongreso = congrCongreso;
    }
    public CongrTrabajoAcademico getCongrTrabajoAcademico() {
        return this.congrTrabajoAcademico;
    }
    
    public void setCongrTrabajoAcademico(CongrTrabajoAcademico congrTrabajoAcademico) {
        this.congrTrabajoAcademico = congrTrabajoAcademico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Blob getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Blob archivo) {
        this.archivo = archivo;
    }




}


