package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CongrTrabajoAcademico generated by hbm2java
 */
public class CongrTrabajoAcademico  implements java.io.Serializable {


     private BigDecimal idTrabajoAcademico;
     private CongrCongreso congrCongreso;
     private CongrEjeTematico congrEjeTematico;
     private CongrSesion congrSesion;
     private CongrTipoTrabajoAcademico congrTipoTrabajoAcademico;
     private String nombreTrabajo;
     private String resumen;
     private Set congrAutors = new HashSet(0);
     private Set congrAdjuntos = new HashSet(0);

    public CongrTrabajoAcademico() {
    }

	
    public CongrTrabajoAcademico(BigDecimal idTrabajoAcademico, CongrCongreso congrCongreso, CongrEjeTematico congrEjeTematico, CongrTipoTrabajoAcademico congrTipoTrabajoAcademico, String nombreTrabajo) {
        this.idTrabajoAcademico = idTrabajoAcademico;
        this.congrCongreso = congrCongreso;
        this.congrEjeTematico = congrEjeTematico;
        this.congrTipoTrabajoAcademico = congrTipoTrabajoAcademico;
        this.nombreTrabajo = nombreTrabajo;
    }
    public CongrTrabajoAcademico(BigDecimal idTrabajoAcademico, CongrCongreso congrCongreso, CongrEjeTematico congrEjeTematico, CongrSesion congrSesion, CongrTipoTrabajoAcademico congrTipoTrabajoAcademico, String nombreTrabajo, String resumen, Set congrAutors, Set congrAdjuntos) {
       this.idTrabajoAcademico = idTrabajoAcademico;
       this.congrCongreso = congrCongreso;
       this.congrEjeTematico = congrEjeTematico;
       this.congrSesion = congrSesion;
       this.congrTipoTrabajoAcademico = congrTipoTrabajoAcademico;
       this.nombreTrabajo = nombreTrabajo;
       this.resumen = resumen;
       this.congrAutors = congrAutors;
       this.congrAdjuntos = congrAdjuntos;
    }
   
    public BigDecimal getIdTrabajoAcademico() {
        return this.idTrabajoAcademico;
    }
    
    public void setIdTrabajoAcademico(BigDecimal idTrabajoAcademico) {
        this.idTrabajoAcademico = idTrabajoAcademico;
    }
    public CongrCongreso getCongrCongreso() {
        return this.congrCongreso;
    }
    
    public void setCongrCongreso(CongrCongreso congrCongreso) {
        this.congrCongreso = congrCongreso;
    }
    public CongrEjeTematico getCongrEjeTematico() {
        return this.congrEjeTematico;
    }
    
    public void setCongrEjeTematico(CongrEjeTematico congrEjeTematico) {
        this.congrEjeTematico = congrEjeTematico;
    }
    public CongrSesion getCongrSesion() {
        return this.congrSesion;
    }
    
    public void setCongrSesion(CongrSesion congrSesion) {
        this.congrSesion = congrSesion;
    }
    public CongrTipoTrabajoAcademico getCongrTipoTrabajoAcademico() {
        return this.congrTipoTrabajoAcademico;
    }
    
    public void setCongrTipoTrabajoAcademico(CongrTipoTrabajoAcademico congrTipoTrabajoAcademico) {
        this.congrTipoTrabajoAcademico = congrTipoTrabajoAcademico;
    }
    public String getNombreTrabajo() {
        return this.nombreTrabajo;
    }
    
    public void setNombreTrabajo(String nombreTrabajo) {
        this.nombreTrabajo = nombreTrabajo;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }
    public Set getCongrAutors() {
        return this.congrAutors;
    }
    
    public void setCongrAutors(Set congrAutors) {
        this.congrAutors = congrAutors;
    }
    public Set getCongrAdjuntos() {
        return this.congrAdjuntos;
    }
    
    public void setCongrAdjuntos(Set congrAdjuntos) {
        this.congrAdjuntos = congrAdjuntos;
    }




}


