package entidades;
// Generated 27/06/2016 06:34:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CongrTipoTrabajoAcademico generated by hbm2java
 */
public class CongrTipoTrabajoAcademico  implements java.io.Serializable {


     private byte idTipoTrabajoAcademico;
     private String nombreTipoTrabajoAcademico;
     private Set congrTrabajoAcademicos = new HashSet(0);

    public CongrTipoTrabajoAcademico() {
    }

	
    public CongrTipoTrabajoAcademico(byte idTipoTrabajoAcademico) {
        this.idTipoTrabajoAcademico = idTipoTrabajoAcademico;
    }
    public CongrTipoTrabajoAcademico(byte idTipoTrabajoAcademico, String nombreTipoTrabajoAcademico, Set congrTrabajoAcademicos) {
       this.idTipoTrabajoAcademico = idTipoTrabajoAcademico;
       this.nombreTipoTrabajoAcademico = nombreTipoTrabajoAcademico;
       this.congrTrabajoAcademicos = congrTrabajoAcademicos;
    }
   
    public byte getIdTipoTrabajoAcademico() {
        return this.idTipoTrabajoAcademico;
    }
    
    public void setIdTipoTrabajoAcademico(byte idTipoTrabajoAcademico) {
        this.idTipoTrabajoAcademico = idTipoTrabajoAcademico;
    }
    public String getNombreTipoTrabajoAcademico() {
        return this.nombreTipoTrabajoAcademico;
    }
    
    public void setNombreTipoTrabajoAcademico(String nombreTipoTrabajoAcademico) {
        this.nombreTipoTrabajoAcademico = nombreTipoTrabajoAcademico;
    }
    public Set getCongrTrabajoAcademicos() {
        return this.congrTrabajoAcademicos;
    }
    
    public void setCongrTrabajoAcademicos(Set congrTrabajoAcademicos) {
        this.congrTrabajoAcademicos = congrTrabajoAcademicos;
    }




}


