package entidades;
// Generated 27/06/2016 06:34:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CongrCongreso generated by hbm2java
 */
public class CongrCongreso  implements java.io.Serializable {


     private BigDecimal idCongreso;
     private String nombre;
     private Set congrTrabajoAcademicos = new HashSet(0);
     private Set congrSesions = new HashSet(0);
     private Set congrSalas = new HashSet(0);
     private Set congrAdjuntos = new HashSet(0);
     private Set congrEjeTematicos = new HashSet(0);

    public CongrCongreso() {
    }

	
    public CongrCongreso(BigDecimal idCongreso, String nombre) {
        this.idCongreso = idCongreso;
        this.nombre = nombre;
    }
    public CongrCongreso(BigDecimal idCongreso, String nombre, Set congrTrabajoAcademicos, Set congrSesions, Set congrSalas, Set congrAdjuntos, Set congrEjeTematicos) {
       this.idCongreso = idCongreso;
       this.nombre = nombre;
       this.congrTrabajoAcademicos = congrTrabajoAcademicos;
       this.congrSesions = congrSesions;
       this.congrSalas = congrSalas;
       this.congrAdjuntos = congrAdjuntos;
       this.congrEjeTematicos = congrEjeTematicos;
    }
   
    public BigDecimal getIdCongreso() {
        return this.idCongreso;
    }
    
    public void setIdCongreso(BigDecimal idCongreso) {
        this.idCongreso = idCongreso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCongrTrabajoAcademicos() {
        return this.congrTrabajoAcademicos;
    }
    
    public void setCongrTrabajoAcademicos(Set congrTrabajoAcademicos) {
        this.congrTrabajoAcademicos = congrTrabajoAcademicos;
    }
    public Set getCongrSesions() {
        return this.congrSesions;
    }
    
    public void setCongrSesions(Set congrSesions) {
        this.congrSesions = congrSesions;
    }
    public Set getCongrSalas() {
        return this.congrSalas;
    }
    
    public void setCongrSalas(Set congrSalas) {
        this.congrSalas = congrSalas;
    }
    public Set getCongrAdjuntos() {
        return this.congrAdjuntos;
    }
    
    public void setCongrAdjuntos(Set congrAdjuntos) {
        this.congrAdjuntos = congrAdjuntos;
    }
    public Set getCongrEjeTematicos() {
        return this.congrEjeTematicos;
    }
    
    public void setCongrEjeTematicos(Set congrEjeTematicos) {
        this.congrEjeTematicos = congrEjeTematicos;
    }




}


