package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CongrModerador generated by hbm2java
 */
public class CongrModerador  implements java.io.Serializable {


     private BigDecimal idModerador;
     private String nombre;
     private String apellidos;
     private String institucion;
     private String codigoNacion;
     private Set congrSesions = new HashSet(0);

    public CongrModerador() {
    }

	
    public CongrModerador(BigDecimal idModerador, String nombre, String apellidos, String codigoNacion) {
        this.idModerador = idModerador;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.codigoNacion = codigoNacion;
    }
    public CongrModerador(BigDecimal idModerador, String nombre, String apellidos, String institucion, String codigoNacion, Set congrSesions) {
       this.idModerador = idModerador;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.institucion = institucion;
       this.codigoNacion = codigoNacion;
       this.congrSesions = congrSesions;
    }
   
    public BigDecimal getIdModerador() {
        return this.idModerador;
    }
    
    public void setIdModerador(BigDecimal idModerador) {
        this.idModerador = idModerador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public String getCodigoNacion() {
        return this.codigoNacion;
    }
    
    public void setCodigoNacion(String codigoNacion) {
        this.codigoNacion = codigoNacion;
    }
    public Set getCongrSesions() {
        return this.congrSesions;
    }
    
    public void setCongrSesions(Set congrSesions) {
        this.congrSesions = congrSesions;
    }




}


