package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CongrSesion generated by hbm2java
 */
public class CongrSesion  implements java.io.Serializable {


     private BigDecimal idSesion;
     private CongrCongreso congrCongreso;
     private CongrModerador congrModerador;
     private CongrSala congrSala;
     private Date fechaDesde;
     private Date fechaHasta;
     private String descripcionSesion;
     private Byte tipoSesion;
     private Set congrTrabajoAcademicos = new HashSet(0);

    public CongrSesion() {
    }

	
    public CongrSesion(BigDecimal idSesion, CongrCongreso congrCongreso, Date fechaDesde, Date fechaHasta, String descripcionSesion) {
        this.idSesion = idSesion;
        this.congrCongreso = congrCongreso;
        this.fechaDesde = fechaDesde;
        this.fechaHasta = fechaHasta;
        this.descripcionSesion = descripcionSesion;
    }
    public CongrSesion(BigDecimal idSesion, CongrCongreso congrCongreso, CongrModerador congrModerador, CongrSala congrSala, Date fechaDesde, Date fechaHasta, String descripcionSesion, Byte tipoSesion, Set congrTrabajoAcademicos) {
       this.idSesion = idSesion;
       this.congrCongreso = congrCongreso;
       this.congrModerador = congrModerador;
       this.congrSala = congrSala;
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.descripcionSesion = descripcionSesion;
       this.tipoSesion = tipoSesion;
       this.congrTrabajoAcademicos = congrTrabajoAcademicos;
    }
   
    public BigDecimal getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(BigDecimal idSesion) {
        this.idSesion = idSesion;
    }
    public CongrCongreso getCongrCongreso() {
        return this.congrCongreso;
    }
    
    public void setCongrCongreso(CongrCongreso congrCongreso) {
        this.congrCongreso = congrCongreso;
    }
    public CongrModerador getCongrModerador() {
        return this.congrModerador;
    }
    
    public void setCongrModerador(CongrModerador congrModerador) {
        this.congrModerador = congrModerador;
    }
    public CongrSala getCongrSala() {
        return this.congrSala;
    }
    
    public void setCongrSala(CongrSala congrSala) {
        this.congrSala = congrSala;
    }
    public Date getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
    public String getDescripcionSesion() {
        return this.descripcionSesion;
    }
    
    public void setDescripcionSesion(String descripcionSesion) {
        this.descripcionSesion = descripcionSesion;
    }
    public Byte getTipoSesion() {
        return this.tipoSesion;
    }
    
    public void setTipoSesion(Byte tipoSesion) {
        this.tipoSesion = tipoSesion;
    }
    public Set getCongrTrabajoAcademicos() {
        return this.congrTrabajoAcademicos;
    }
    
    public void setCongrTrabajoAcademicos(Set congrTrabajoAcademicos) {
        this.congrTrabajoAcademicos = congrTrabajoAcademicos;
    }




}


