package entidades;
// Generated 27/06/2016 06:34:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CongrEjeTematico generated by hbm2java
 */
public class CongrEjeTematico  implements java.io.Serializable {


     private BigDecimal idEjeTematico;
     private CongrCongreso congrCongreso;
     private String nombre;
     private String descripcion;
     private Set congrTrabajoAcademicos = new HashSet(0);

    public CongrEjeTematico() {
    }

	
    public CongrEjeTematico(BigDecimal idEjeTematico, CongrCongreso congrCongreso, String nombre, String descripcion) {
        this.idEjeTematico = idEjeTematico;
        this.congrCongreso = congrCongreso;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public CongrEjeTematico(BigDecimal idEjeTematico, CongrCongreso congrCongreso, String nombre, String descripcion, Set congrTrabajoAcademicos) {
       this.idEjeTematico = idEjeTematico;
       this.congrCongreso = congrCongreso;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.congrTrabajoAcademicos = congrTrabajoAcademicos;
    }
   
    public BigDecimal getIdEjeTematico() {
        return this.idEjeTematico;
    }
    
    public void setIdEjeTematico(BigDecimal idEjeTematico) {
        this.idEjeTematico = idEjeTematico;
    }
    public CongrCongreso getCongrCongreso() {
        return this.congrCongreso;
    }
    
    public void setCongrCongreso(CongrCongreso congrCongreso) {
        this.congrCongreso = congrCongreso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCongrTrabajoAcademicos() {
        return this.congrTrabajoAcademicos;
    }
    
    public void setCongrTrabajoAcademicos(Set congrTrabajoAcademicos) {
        this.congrTrabajoAcademicos = congrTrabajoAcademicos;
    }




}


