package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ExpPersona generated by hbm2java
 */
public class ExpPersona  implements java.io.Serializable {


     private ExpPersonaId id;
     private AdmTipoIdentificacion admTipoIdentificacion;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private Set segUsuarios = new HashSet(0);

    public ExpPersona() {
    }

	
    public ExpPersona(ExpPersonaId id, AdmTipoIdentificacion admTipoIdentificacion) {
        this.id = id;
        this.admTipoIdentificacion = admTipoIdentificacion;
    }
    public ExpPersona(ExpPersonaId id, AdmTipoIdentificacion admTipoIdentificacion, String nombre, String primerApellido, String segundoApellido, Set segUsuarios) {
       this.id = id;
       this.admTipoIdentificacion = admTipoIdentificacion;
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.segUsuarios = segUsuarios;
    }
   
    public ExpPersonaId getId() {
        return this.id;
    }
    
    public void setId(ExpPersonaId id) {
        this.id = id;
    }
    public AdmTipoIdentificacion getAdmTipoIdentificacion() {
        return this.admTipoIdentificacion;
    }
    
    public void setAdmTipoIdentificacion(AdmTipoIdentificacion admTipoIdentificacion) {
        this.admTipoIdentificacion = admTipoIdentificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public Set getSegUsuarios() {
        return this.segUsuarios;
    }
    
    public void setSegUsuarios(Set segUsuarios) {
        this.segUsuarios = segUsuarios;
    }




}


