package entidades;
// Generated 27/06/2016 06:34:06 PM by Hibernate Tools 4.3.1



/**
 * ExpPersonaId generated by hbm2java
 */
public class ExpPersonaId  implements java.io.Serializable {


     private String idPersona;
     private byte idTipoIdentificacion;

    public ExpPersonaId() {
    }

    public ExpPersonaId(String idPersona, byte idTipoIdentificacion) {
       this.idPersona = idPersona;
       this.idTipoIdentificacion = idTipoIdentificacion;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public byte getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(byte idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExpPersonaId) ) return false;
		 ExpPersonaId castOther = ( ExpPersonaId ) other; 
         
		 return ( (this.getIdPersona()==castOther.getIdPersona()) || ( this.getIdPersona()!=null && castOther.getIdPersona()!=null && this.getIdPersona().equals(castOther.getIdPersona()) ) )
 && (this.getIdTipoIdentificacion()==castOther.getIdTipoIdentificacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPersona() == null ? 0 : this.getIdPersona().hashCode() );
         result = 37 * result + this.getIdTipoIdentificacion();
         return result;
   }   


}


