package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SegPermiso generated by hbm2java
 */
public class SegPermiso  implements java.io.Serializable {


     private BigDecimal idPermiso;
     private String nombrePermiso;
     private String descripcion;
     private Set segRols = new HashSet(0);

    public SegPermiso() {
    }

	
    public SegPermiso(BigDecimal idPermiso, String nombrePermiso, String descripcion) {
        this.idPermiso = idPermiso;
        this.nombrePermiso = nombrePermiso;
        this.descripcion = descripcion;
    }
    public SegPermiso(BigDecimal idPermiso, String nombrePermiso, String descripcion, Set segRols) {
       this.idPermiso = idPermiso;
       this.nombrePermiso = nombrePermiso;
       this.descripcion = descripcion;
       this.segRols = segRols;
    }
   
    public BigDecimal getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(BigDecimal idPermiso) {
        this.idPermiso = idPermiso;
    }
    public String getNombrePermiso() {
        return this.nombrePermiso;
    }
    
    public void setNombrePermiso(String nombrePermiso) {
        this.nombrePermiso = nombrePermiso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSegRols() {
        return this.segRols;
    }
    
    public void setSegRols(Set segRols) {
        this.segRols = segRols;
    }




}


