package entidades;
// Generated 27/06/2016 06:34:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegUsuario generated by hbm2java
 */
public class SegUsuario  implements java.io.Serializable {


     private String idUsuario;
     private ExpPersona expPersona;
     private boolean tipoUsuario;
     private Date activoDesde;
     private Date activoHasta;
     private boolean activo;
     private Set segRols = new HashSet(0);
     private SegUsuarioInterno segUsuarioInterno;

    public SegUsuario() {
    }

	
    public SegUsuario(String idUsuario, ExpPersona expPersona, boolean tipoUsuario, Date activoDesde, Date activoHasta, boolean activo) {
        this.idUsuario = idUsuario;
        this.expPersona = expPersona;
        this.tipoUsuario = tipoUsuario;
        this.activoDesde = activoDesde;
        this.activoHasta = activoHasta;
        this.activo = activo;
    }
    public SegUsuario(String idUsuario, ExpPersona expPersona, boolean tipoUsuario, Date activoDesde, Date activoHasta, boolean activo, Set segRols, SegUsuarioInterno segUsuarioInterno) {
       this.idUsuario = idUsuario;
       this.expPersona = expPersona;
       this.tipoUsuario = tipoUsuario;
       this.activoDesde = activoDesde;
       this.activoHasta = activoHasta;
       this.activo = activo;
       this.segRols = segRols;
       this.segUsuarioInterno = segUsuarioInterno;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public ExpPersona getExpPersona() {
        return this.expPersona;
    }
    
    public void setExpPersona(ExpPersona expPersona) {
        this.expPersona = expPersona;
    }
    public boolean isTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(boolean tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Date getActivoDesde() {
        return this.activoDesde;
    }
    
    public void setActivoDesde(Date activoDesde) {
        this.activoDesde = activoDesde;
    }
    public Date getActivoHasta() {
        return this.activoHasta;
    }
    
    public void setActivoHasta(Date activoHasta) {
        this.activoHasta = activoHasta;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getSegRols() {
        return this.segRols;
    }
    
    public void setSegRols(Set segRols) {
        this.segRols = segRols;
    }
    public SegUsuarioInterno getSegUsuarioInterno() {
        return this.segUsuarioInterno;
    }
    
    public void setSegUsuarioInterno(SegUsuarioInterno segUsuarioInterno) {
        this.segUsuarioInterno = segUsuarioInterno;
    }




}


