package entidades;
// Generated 04/07/2016 10:19:44 PM by Hibernate Tools 4.3.1



/**
 * SegUsuarioInterno generated by hbm2java
 */
public class SegUsuarioInterno  implements java.io.Serializable {


     private String idUsuario;
     private SegUsuario segUsuario;
     private String nombreCompleto;
     private String correoElectronico;
     private String clave;

    public SegUsuarioInterno() {
    }

    public SegUsuarioInterno(SegUsuario segUsuario, String nombreCompleto, String correoElectronico, String clave) {
       this.segUsuario = segUsuario;
       this.nombreCompleto = nombreCompleto;
       this.correoElectronico = correoElectronico;
       this.clave = clave;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


